global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: api
    metrics_path: /actuator/prometheus
    dns_sd_configs:
      - names: [api]
        type: A
        port: 9001
  - job_name: workers
    dns_sd_configs:
      - names: [worker, reaper]
        type: A
        port: 9102
